version: '3.1'

services:

  db:
    image: mariadb:10.5.8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tagger
      MYSQL_USER: tagger
      MYSQL_PASSWORD: tagger

  tagger:
    build:
      context: .
      dockerfile: Dockerfile
    image: tagger
    restart: always
    ports:
      - 80:80
